$env:PORT=5000
$env:SUPABASE_URL='https://qjmirmenxsmxlqtcihkh.supabase.co'
$env:SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbWlybWVueHNteGxxdGNpaGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTU2MTEsImV4cCI6MjA4NjQzMTYxMX0.ohMCmSXRXIB_0TZ6QJTqxE_j7EM84nGxwHeY3agZqKE'
$env:SUPABASE_SERVICE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbWlybWVueHNteGxxdGNpaGtoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDg1NTYxMSwiZXhwIjoyMDg2NDMxNjExfQ.n3NN_MkFpADrvd-aDPkynIJFf3WVWwdcqo02XlIKs04'
$env:JWT_SECRET='dev_jwt_secret_key_12345'
$env:NODE_ENV='development'

npm run dev
